<script lang="ts">
	export let width: string = '354';
	export let height: string = '100%';
</script>

<svg {width} {height} viewBox="0 0 1024 1024" fill="none" xmlns="http://www.w3.org/2000/svg">
	<g clip-path="url(#clip0_1622_4971)">
		<g filter="url(#filter0_d_1622_4971)">
			<path
				d="M738.325 476.588C803.016 476.588 855.459 529.031 855.459 593.722C855.459 658.414 803.016 710.857 738.325 710.857C673.633 710.857 621.19 658.414 621.19 593.722C621.19 529.031 673.633 476.588 738.325 476.588Z"
				fill="#9C44FF"
				stroke="#9C44FF"
				stroke-width="13"
				class="svg-elem-1"
			></path>
			<path
				d="M680.417 98.5L677.426 107.129C640.257 214.346 605.303 322.907 570.338 431.502C548.985 497.82 527.629 564.151 505.773 630.154L505.76 630.195L505.745 630.237C495.381 660.179 484.976 690.241 473.407 720.318L473.389 720.366L473.369 720.413C456.699 761.8 435.679 812.705 405.278 853.238C374.783 893.898 334.189 924.972 278.375 924.972C260.875 924.972 237.778 921.082 215.804 914.782C193.901 908.503 172.3 899.601 158.137 889.133L153.905 886.005L156.083 881.216L202.172 779.819L205.242 773.064L211.534 776.997C229.042 787.939 249.754 794.445 270.31 794.445C280.14 794.445 289.317 789.744 297.952 781.158C306.623 772.537 314.308 760.407 320.913 746.704C333.734 720.108 341.849 688.946 345.415 670.076L282.63 485.854L281.939 483.827L282.588 481.787L346.076 282.088L352.352 262.349L358.479 282.134L417.734 473.442L530.254 103.11L531.655 98.5H680.417Z"
				fill="white"
				stroke="white"
				stroke-width="13"
				class="svg-elem-2"
			></path>
		</g>
	</g>
	<defs>
		<filter
			id="filter0_d_1622_4971"
			x="118.806"
			y="82.9982"
			width="770.159"
			height="893.483"
			filterUnits="userSpaceOnUse"
			color-interpolation-filters="sRGB"
		>
			<feFlood flood-opacity="0" result="BackgroundImageFix"></feFlood>
			<feColorMatrix
				in="SourceAlpha"
				type="matrix"
				values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
				result="hardAlpha"
			></feColorMatrix>
			<feOffset dy="18.0035"></feOffset>
			<feGaussianBlur stdDeviation="13.5027"></feGaussianBlur>
			<feComposite in2="hardAlpha" operator="out"></feComposite>
			<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"
			></feColorMatrix>
			<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_1622_4971"
			></feBlend>
			<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_1622_4971" result="shape"
			></feBlend>
		</filter>
		<clipPath id="clip0_1622_4971">
			<rect width="1024" height="1024" fill="white" class="svg-elem-3"></rect>
		</clipPath>
	</defs>
</svg>

<style>
	/***************************************************
 * Generated by SVG Artista on 7/21/2025, 4:23:53 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

	@-webkit-keyframes animate-svg-stroke-1 {
		0% {
			stroke-dashoffset: 738.0819091796875px;
			stroke-dasharray: 738.0819091796875px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 738.0819091796875px;
		}
	}

	@keyframes animate-svg-stroke-1 {
		0% {
			stroke-dashoffset: 738.0819091796875px;
			stroke-dasharray: 738.0819091796875px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 738.0819091796875px;
		}
	}

	@-webkit-keyframes animate-svg-fill-1 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(156, 68, 255);
		}
	}

	@keyframes animate-svg-fill-1 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(156, 68, 255);
		}
	}

	.svg-elem-1 {
		-webkit-animation:
			animate-svg-stroke-1 1s ease-out 0.5s both,
			animate-svg-fill-1 0.7s ease-in-out 0.8s both;
		animation:
			animate-svg-stroke-1 1s ease-out 0.5s both,
			animate-svg-fill-1 0.7s ease-in-out 0.8s both;
	}

	@-webkit-keyframes animate-svg-stroke-2 {
		0% {
			stroke-dashoffset: 2629.15185546875px;
			stroke-dasharray: 2629.15185546875px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 2629.15185546875px;
		}
	}

	@keyframes animate-svg-stroke-2 {
		0% {
			stroke-dashoffset: 2629.15185546875px;
			stroke-dasharray: 2629.15185546875px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 2629.15185546875px;
		}
	}

	@-webkit-keyframes animate-svg-fill-2 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(255, 255, 255);
		}
	}

	@keyframes animate-svg-fill-2 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(255, 255, 255);
		}
	}

	.svg-elem-2 {
		-webkit-animation:
			animate-svg-stroke-2 1s ease-out 0.62s both,
			animate-svg-fill-2 0.7s ease-in-out 0.9s both;
		animation:
			animate-svg-stroke-2 1s ease-out 0.62s both,
			animate-svg-fill-2 0.7s ease-in-out 0.9s both;
	}

	@-webkit-keyframes animate-svg-stroke-3 {
		0% {
			stroke-dashoffset: 4098px;
			stroke-dasharray: 4098px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 4098px;
		}
	}

	@keyframes animate-svg-stroke-3 {
		0% {
			stroke-dashoffset: 4098px;
			stroke-dasharray: 4098px;
		}

		100% {
			stroke-dashoffset: 0;
			stroke-dasharray: 4098px;
		}
	}

	@-webkit-keyframes animate-svg-fill-3 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(255, 255, 255);
		}
	}

	@keyframes animate-svg-fill-3 {
		0% {
			fill: transparent;
		}

		100% {
			fill: rgb(255, 255, 255);
		}
	}

	.svg-elem-3 {
		-webkit-animation:
			animate-svg-stroke-3 1s ease-out 0.74s both,
			animate-svg-fill-3 0.7s ease-in-out 1s both;
		animation:
			animate-svg-stroke-3 1s ease-out 0.74s both,
			animate-svg-fill-3 0.7s ease-in-out 1s both;
	}
</style>
